### PR TITLE
initial submit of max plus eigenvalue

### PR DESCRIPTION
**Pull request by fxc20001**
Hi Prof. Arjun,

I wrote some codes for max plus eigenvalues. I am not quite sure if matrix A is implemented correctly.

Best,
Xuchen

### CODE REVIEW

**Comment by fxc20001** [comment]
Screen Shot 2021-07-03 at 2 06 19 PM
Screen Shot 2021-07-03 at 2 05 50 PM

**Comment by arjunkc** [comment]
[2021-07-03-Note-22-03 matrix formation.pdf](https://github.com/arjunkc/busemann-code/files/6759263/2021-07-03-Note-22-03.matrix.formation.pdf)

Hi xuchen I have draw the matrix that corresponds to the graph above, for the parameters (1,1). Can you try to debug? Does it make sense? I made the edge weights positive by removing the negative sign.

**Comment by fxc20001** [comment]
Screen Shot 2021-07-04 at 9 30 08 PM
Screen Shot 2021-07-04 at 9 29 56 PM
Hi Prof. Arjun, do you mean like this?

**Comment by arjunkc** [comment]
Yep, looks good!

**Comment by fxc20001** [comment]
So is the rest part correct or need debugging

**Comment by arjunkc** [comment]
You mean the code for the eigenvalue? There is only one way to find out:
let's get it to find the eigenvalue and see if its the same as gpl,
right? We can continue debugging and testing, or we can just incorporate
the code for the A matrix.

Quoting fxc20001 (2021-07-04 22:39:09)

**Comment by fxc20001** [comment]
They are different. I turned time to be positive for gpl. I should have followed the pseudocode on the book.
Screen Shot 2021-07-05 at 1 48 03 PM

**Comment by fxc20001** [comment]
Hi Prof. Arjun, I have modified my code and it should assign all but the outer vertices to matrix A.

**Comment by arjunkc** [comment]
Can you give me a picture of a matrix for m=2 or m=3 with N=5 say?

Quoting fxc20001 (2021-07-08 17:40:24)

**Comment by fxc20001** [comment]
Screen Shot 2021-07-08 at 7 11 40 PM
Screen Shot 2021-07-08 at 7 11 56 PM

**Pull request merged**
