### PR TITLE
vertex weights

### PR DESCRIPTION
**Pull request by fxc20001**

### CODE REVIEW

**Comment by arjunkc** [comment]
Can you remove settings.json and lppsim.cpython-38.pyc from the commit?

Also, can you add a description to get_idArr and say something like (on line after def get_idArr)
"""
This function returns an array of edge ids in an NxN box of the form i+p*(m-1)... <please fill in rest of description>
The variable d is used to distinguish between horizontal and vertical edges.
m is the period.
"""

In fact, in get_idArr, it's best to rename the variable d to something like direction or something so that it is more descriptive. 

Otherwise it looks good!

Thanks!

**Comment by arjunkc** [comment]
Can you also change wtfun_periodic to something more descriptive like wt_generator or something. It would be helpful to add comments to this too.

**Comment by fxc20001** [comment]
All commits are pushed to revert-1-master branch not the master branch. Sorry about that. For graph shape = triangle, the periodic weight assignments are generated by giving random weights to a N_small = m triangle graph, periodically assign edges that are m distances away. There are some edges that could not be assigned by periodic assignment so I randomize their weights both vertex and edge weights are implemented. I have also added an extra parameter so user could choose which random function they would like when generate tempWeight in the code.

**Comment by arjunkc** [comment]
Ok, most of it looks good. Great work!

For the triangle grid, could you just use the periodic square?  The triangular grid just aids large N computations for the limit shape. Does this make sense?

Once done, can you also post a pic (or email me) of the graph with labeled weights generated for the following test cases (m=2, N = 7 for example)

1. rectangular, vertex weights
2. rectangular, edge weights
3. triangle, vertex weights
4. triangle, edge weights

I also don't like the "missed weights" part. If assigned correctly, why would you use the missed weights part at all?

**Comment by arjunkc** [comment]
Also, can you change the random function from normal to uniform. I'm just a bit suspicious of the negative weights. `np.random.uniform`

**Comment by fxc20001** [comment]
For triangle grid, do you mean a size m periodic square as the square in the periodic square lattice. The missed part is because if we use triangle shape as the base weights in periodic settings, those edges in the square lattice containing the triangle base shape would not be given weights. This could be addressed once we changed from triangle base to square base.

**Comment by arjunkc** [comment]
Let's just use a square base shape that we periodize for both the triangle and rectangular graph shapes.

**Comment by arjunkc** [comment]
Ok, looks good. Post the pics when you get a chance!

**Pull request merged**
