### PR TITLE
gpl, time constant plots

### PR DESCRIPTION
**Pull request by fxc20001**

### CODE REVIEW

**Comment by fxc20001** [comment]
_N5000_rectangle_edge_4
_N5000_rectangle_edge_5
_N5000_rectangle_edge_6
_N5000_rectangle_edge_7
_N5000_rectangle_edge_8
_N5000_rectangle_edge_9
_N5000_rectangle_edge_10
_N5000_rectangle_edge_11
_N5000_rectangle_edge_12
_N5000_rectangle_edge_13
_N5000_rectangle_edge_14
_N5000_rectangle_edge_15
_N5000_rectangle_edge_16
_N5000_rectangle_edge_17
_N5000_rectangle_edge_18
_N5000_rectangle_edge_19
_N5000_rectangle_edge_20
_N5000_rectangle_edge_21
_N5000_rectangle_edge_22
_N5000_rectangle_edge_23
_N5000_rectangle_edge_24
_N5000_rectangle_edge_25
_N5000_rectangle_edge_26
_N5000_rectangle_edge_27
_N5000_rectangle_edge_28
_N5000_rectangle_edge_29
_N5000_rectangle_edge_30

**Comment by fxc20001** [comment]
_N5000_rectangle_edge_5

**Comment by arjunkc** [comment]
Thanks! Good work. Can you post a pic of gpl too?

**Comment by fxc20001** [comment]
For gpl, plot one for each m=4,..,30 right or just one specific period.

**Comment by arjunkc** [comment]
Just one specific period would be good, just to see if it works.

**Comment by fxc20001** [comment]
Screen Shot 2021-06-25 at 1 08 29 AM
Is it what is supposed to be? The plot is for m=11

**Comment by arjunkc** [comment]
I would need to see both gpp and gpl simultaneously. Basically they're convex duals. So one should be able to see if its correct based on this. It's hard to see them across runs because the weights are resampled. Also, change hrange to like 2 or 3, 100 is too big.

**Comment by fxc20001** [comment]
Screen Shot 2021-06-27 at 2 55 15 PM
m = 11, h=5

**Comment by arjunkc** [comment]
Yeah, that looks right. For convex duals the sharp corners will be associated with flat lines and vice versa.

**Pull request merged**
